# Generated by Django 5.2.5 on 2025-09-22 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0009_remove_employeedirectory_absences_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeedirectory',
            old_name='employee_no',
            new_name='employee_code',
        ),
        migrations.RemoveField(
            model_name='employeedirectory',
            name='data',
        ),
        migrations.AddField(
            model_name='employeedirectory',
            name='absences',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedirectory',
            name='back_pay_sl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedirectory',
            name='back_pay_vl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedirectory',
            name='leg_h_on_rest_day',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedirectory',
            name='legal_holiday',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedirectory',
            name='nd_leg_h_on_rest_excess',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedirectory',
            name='nd_leg_h_on_restday',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedirectory',
            name='nd_legal_holiday',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedirectory',
            name='nd_leghol_excess',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedirectory',
            name='nd_ot_reg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedirectory',
            name='nd_ot_reg_excess',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedirectory',
            name='nd_reg_hrs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedirectory',
            name='nd_rest_excess',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedirectory',
            name='nd_restday',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedirectory',
            name='nd_sh_on_rest',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedirectory',
            name='nd_sh_on_rest_excess',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedirectory',
            name='nd_shday_excess',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedirectory',
            name='nd_special_hday',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedirectory',
            name='ot_leg_h_on_rest_excess',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedirectory',
            name='ot_legal_holiday',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedirectory',
            name='ot_leghol_excess',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedirectory',
            name='ot_regular',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedirectory',
            name='ot_regular_excess',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedirectory',
            name='ot_rest_excess',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedirectory',
            name='ot_restday',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedirectory',
            name='ot_sh_on_rest',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedirectory',
            name='ot_sh_on_rest_excess',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedirectory',
            name='ot_shday_excess',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedirectory',
            name='ot_special_hday',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedirectory',
            name='overnight_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedirectory',
            name='project',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employeedirectory',
            name='sickleave_applied',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedirectory',
            name='special_holiday',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedirectory',
            name='tardiness',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedirectory',
            name='total_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedirectory',
            name='undertime',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedirectory',
            name='vacleave_applied',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
