# Generated by Django 5.2.5 on 2025-09-23 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0011_alter_employeedirectory_absences_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedirectory',
            name='employee_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
