# Generated by Django 5.2.5 on 2025-09-24 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0012_alter_employeedirectory_employee_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DTRFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='dtr/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DTREntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_initial', models.CharField(blank=True, max_length=5, null=True)),
                ('employee_no', models.CharField(max_length=50)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('daily_data', models.JSONField(default=dict)),
                ('total_days', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('total_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('regular_ot', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('legal_holiday', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('legal_holiday_ot', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('special_holiday', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('special_holiday_ot', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('night_diff', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('undertime_minutes', models.IntegerField(default=0)),
                ('dtr_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='files.dtrfile')),
            ],
        ),
    ]
