# Generated by Django 5.2.5 on 2025-09-24 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0013_dtrfile_dtrentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='dtrfile',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dtrfile',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
