# Generated by Django 5.2.5 on 2025-09-24 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0014_dtrfile_end_date_dtrfile_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dtrentry',
            name='employee_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
