# Generated by Django 5.2.5 on 2025-09-27 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0015_alter_dtrentry_employee_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dtrentry',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='dtrentry',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='dtrentry',
            name='legal_holiday_ot',
        ),
        migrations.RemoveField(
            model_name='dtrentry',
            name='middle_initial',
        ),
        migrations.RemoveField(
            model_name='dtrentry',
            name='special_holiday_ot',
        ),
        migrations.AddField(
            model_name='dtrentry',
            name='full_name',
            field=models.CharField(default='Unnamed Employee', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dtrentry',
            name='unworked_reg_holiday',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
