# Generated by Django 5.2.5 on 2025-09-27 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0016_remove_dtrentry_first_name_remove_dtrentry_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedirectory',
            name='employee_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
