# Generated by Django 5.2.5 on 2025-09-29 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0017_alter_employeedirectory_employee_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedirectory',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedirectory',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='employeedirectory',
            unique_together={('employee_code', 'start_date', 'end_date')},
        ),
    ]
