# Generated by Django 5.2.5 on 2025-09-29 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0018_employeedirectory_end_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employeedirectory',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='employeedirectory',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='employeedirectory',
            name='start_date',
        ),
    ]
