# Generated by Django 5.2.5 on 2025-09-29 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0020_employeedirectory_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedirectory',
            name='date_covered',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
