# Generated by Django 5.2.5 on 2025-09-29 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0022_alter_employeedirectory_employee_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedirectory',
            name='employee_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
