# Generated by Django 5.2.5 on 2025-09-29 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0023_alter_employeedirectory_employee_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employeedirectory',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='employeedirectory',
            name='date_covered',
        ),
        migrations.RemoveField(
            model_name='employeedirectory',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='employeedirectory',
            name='start_date',
        ),
    ]
