# Generated by Django 5.2.5 on 2025-09-29 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0024_alter_employeedirectory_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedirectory',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedirectory',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
