# Generated by Django 5.2.5 on 2025-09-29 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0025_employeedirectory_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeedirectory',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='employeedirectory',
            name='start_date',
        ),
    ]
