# Generated by Django 5.2.5 on 2025-10-01 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0028_updatedemployee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UpdatedEmployee',
        ),
    ]
