# Generated by Django 5.2.5 on 2025-10-02 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0031_rename_area_dtrentry_position_dtrentry_shift_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dtrentry',
            old_name='position',
            new_name='area',
        ),
        migrations.RemoveField(
            model_name='dtrentry',
            name='shift',
        ),
        migrations.RemoveField(
            model_name='dtrentry',
            name='time',
        ),
    ]
