# Generated by Django 5.2.5 on 2025-10-02 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0032_rename_position_dtrentry_area_remove_dtrentry_shift_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dtrentry',
            old_name='area',
            new_name='position',
        ),
        migrations.AddField(
            model_name='dtrentry',
            name='shift',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dtrentry',
            name='time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
