# Generated by Django 5.2.5 on 2025-10-03 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0033_rename_area_dtrentry_position_dtrentry_shift_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dtrfile',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
