# Generated by Django 5.2.5 on 2025-10-03 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0034_dtrfile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedirectory',
            name='employee_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
