# Generated by Django 5.2.5 on 2025-10-22 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0037_pdffile'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdffile',
            name='end_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pdffile',
            name='readable_period',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pdffile',
            name='start_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
