# Generated by Django 5.2.5 on 2025-10-24 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0038_pdffile_end_date_pdffile_readable_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedirectory',
            name='employee_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
