# Generated by Django 5.2.5 on 2025-10-27 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0039_alter_employeedirectory_employee_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdffile',
            name='updated_pdf',
            field=models.FileField(blank=True, null=True, upload_to='updated_pdfs/'),
        ),
    ]
