# Generated by Django 5.2.5 on 2025-12-17 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0040_pdffile_updated_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='dtrfile',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
