# Generated by Django 5.2.5 on 2025-12-18 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0043_dtruploadrequest_delete_dtruploadpermission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DTRUploadRequest',
        ),
    ]
